openapi: 3.0.0
info:
  title: GeoIP Service
  description: A service for validating IP addresses against allowed countries using MaxMind's GeoLite2 database.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /v1/check:
    post:
      summary: Validate IP address against allowed countries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ip_address:
                  type: string
                  format: ipv4
                  description: The IP address to validate
                allowed_countries:
                  type: array
                  items:
                    type: string
                  description: List of allowed country codes
              required:
                - ip_address
                - allowed_countries
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowed:
                    type: boolean
                    description: Whether the IP is allowed
                  country:
                    type: string
                    description: Detected country code
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error code
                  message:
                    type: string
                    description: Error message
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: geoip-service 